import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';
import type { Language } from '@sky-bar/shared';

const messages = {
  de: {
    dashboard:'Übersicht', takeOrders:'Bestellen', orders:'Offene Bestellungen', bills:'Rechnungen', guests:'Gäste', rooms:'Zimmer', products:'Produkte', requests:'Anfragen', account:'Konto', settings:'Betrieb', logout:'Abmelden', total:'Gesamt', items:'Artikel', add:'Hinzufügen', save:'Speichern', cancel:'Abbrechen', confirm:'Bestätigen', close:'Schließen', edit:'Bearbeiten', remove:'Entfernen', print:'Drucken', settle:'Abrechnen', cash:'Bar', card:'Karte', other:'Sonstiges', pending:'Ausstehend', language:'Sprache', offline:'Offline', synced:'Synchronisiert', selectRoom:'Zimmer wählen', selectGuest:'Gast wählen', submitOrder:'Bestellung buchen', empty:'Noch keine Einträge', venueName:'Name des Betriebs', welcome:'Willkommen', guestAccess:'Gastzugang', requestAccess:'Zugang anfragen', selfService:'Selbstbedienung', undo:'Rückgängig', approve:'Genehmigen', deny:'Ablehnen',
    today:'Heute', viewAll:'Alle anzeigen', searchGuests:'Gäste suchen…', selected:'ausgewählt', selectProducts:'Produkte auswählen, um eine Bestellung zu erstellen.', orderQueued:'Bestellung offline gespeichert und zur Synchronisierung vorgemerkt.', orderAdded:'Bestellung hinzugefügt.', note:'Notiz', live:'Live', archive:'Archiv', searchBills:'Nach Gast, Zimmer oder Nummer suchen…', loading:'Wird geladen…', voidBill:'Rechnung stornieren', voided:'Storniert', bill:'Rechnung', guest:'Gast', date:'Datum', host:'Host', reason:'Grund', reversalReason:'Grund für die Stornierung', directory:'Verzeichnis', guestArchiveWarning:'Der Gast wird archiviert und seine Gerätezugänge werden widerrufen. Offene Bestellungen müssen zuerst abgeschlossen werden.', configuration:'Konfiguration', roomName:'Zimmername', displayOrder:'Anzeigereihenfolge', catalog:'Katalog', categories:'Kategorien', germanName:'Deutscher Name', description:'Beschreibung', price:'Preis', category:'Kategorie', enabledForOrders:'Für neue Bestellungen aktiviert', enabled:'Aktiviert', disabled:'Deaktiviert', liveQueue:'Live-Warteschlange', linkGuest:'Gast zuordnen', createGuest:'Neuen Gast erstellen', linkTo:'Zuordnen zu', accessExpires:'Zugang läuft ab', profileCredentials:'Profil & Zugangsdaten', currentPassword:'Aktuelles Passwort', newPassword:'Neues Passwort', passwordHint:'Mindestens 12 Zeichen', loggedInDevices:'Angemeldete Geräte', thisDevice:'Dieses Gerät', lastActive:'Zuletzt aktiv', revoke:'Widerrufen', hostAccounts:'Host-Konten', active:'Aktiv', inactive:'Deaktiviert', enable:'Aktivieren', disable:'Deaktivieren', addHost:'Host hinzufügen', temporaryPassword:'Temporäres Passwort', role:'Rolle', staff:'Mitarbeiter', admin:'Administrator', createAccount:'Konto erstellen', accountUpdated:'Konto aktualisiert.', permissionRequired:'Administratorberechtigung erforderlich.', venueSaved:'Betriebseinstellungen gespeichert. Neue Rechnungen verwenden den aktuellen Namen; historische Rechnungen bleiben unverändert.', venueIdentity:'Betriebsidentität', venueIdentityHelp:'Sky Bar ist der Name der Software. Der Betriebsname erscheint auf Rechnungen und wird bei jeder Abrechnung gespeichert.', defaultLanguage:'Standardsprache', timezone:'Zeitzone', venueGuestAccess:'Gastzugang des Betriebs', roomQrCodes:'Zimmer-QR-Codes', roomPreselected:'Zimmer vorausgewählt', signInDescription:'Sicher anmelden, um den Betrieb zu verwalten.', email:'E-Mail', password:'Passwort', signIn:'Anmelden', hostLogin:'Host-Anmeldung', requestDenied:'Der Host hat diese Anfrage nicht genehmigt.', requestWaiting:'Der Host wurde benachrichtigt. Diese Seite wird automatisch aktualisiert.', itemAdded:'Artikel hinzugefügt', poweredBy:'Bereitgestellt von Sky Bar',
  },
  it: {
    dashboard:'Panoramica', takeOrders:'Ordina', orders:'Ordini aperti', bills:'Conti', guests:'Ospiti', rooms:'Camere', products:'Prodotti', requests:'Richieste', account:'Account', settings:'Locale', logout:'Esci', total:'Totale', items:'Articoli', add:'Aggiungi', save:'Salva', cancel:'Annulla', confirm:'Conferma', close:'Chiudi', edit:'Modifica', remove:'Rimuovi', print:'Stampa', settle:'Incassa', cash:'Contanti', card:'Carta', other:'Altro', pending:'In attesa', language:'Lingua', offline:'Offline', synced:'Sincronizzato', selectRoom:'Scegli camera', selectGuest:'Scegli ospite', submitOrder:'Registra ordine', empty:'Nessun elemento', venueName:'Nome del locale', welcome:'Benvenuto', guestAccess:'Accesso ospite', requestAccess:'Richiedi accesso', selfService:'Self-service', undo:'Annulla', approve:'Approva', deny:'Rifiuta',
    today:'Oggi', viewAll:'Mostra tutto', searchGuests:'Cerca ospiti…', selected:'selezionati', selectProducts:'Seleziona i prodotti per creare un ordine.', orderQueued:'Ordine salvato offline e in coda per la sincronizzazione.', orderAdded:'Ordine aggiunto.', note:'Nota', live:'In tempo reale', archive:'Archivio', searchBills:'Cerca per ospite, camera o numero…', loading:'Caricamento…', voidBill:'Annulla conto', voided:'Annullato', bill:'Conto', guest:'Ospite', date:'Data', host:'Host', reason:'Motivo', reversalReason:'Motivo dell’annullamento', directory:'Elenco', guestArchiveWarning:'L’ospite verrà archiviato e i suoi accessi dispositivo saranno revocati. Prima devono essere chiusi gli ordini aperti.', configuration:'Configurazione', roomName:'Nome camera', displayOrder:'Ordine di visualizzazione', catalog:'Catalogo', categories:'Categorie', germanName:'Nome tedesco', description:'Descrizione', price:'Prezzo', category:'Categoria', enabledForOrders:'Abilitato per nuovi ordini', enabled:'Abilitato', disabled:'Disabilitato', liveQueue:'Coda in tempo reale', linkGuest:'Collega ospite', createGuest:'Crea nuovo ospite', linkTo:'Collega a', accessExpires:'Scadenza accesso', profileCredentials:'Profilo e credenziali', currentPassword:'Password attuale', newPassword:'Nuova password', passwordHint:'Almeno 12 caratteri', loggedInDevices:'Dispositivi connessi', thisDevice:'Questo dispositivo', lastActive:'Ultima attività', revoke:'Revoca', hostAccounts:'Account host', active:'Attivo', inactive:'Disattivato', enable:'Abilita', disable:'Disabilita', addHost:'Aggiungi host', temporaryPassword:'Password temporanea', role:'Ruolo', staff:'Personale', admin:'Amministratore', createAccount:'Crea account', accountUpdated:'Account aggiornato.', permissionRequired:'È richiesta l’autorizzazione di amministratore.', venueSaved:'Impostazioni del locale salvate. I nuovi conti useranno il nome attuale; quelli storici restano invariati.', venueIdentity:'Identità del locale', venueIdentityHelp:'Sky Bar è il nome del software. Il nome del locale appare nei conti e viene salvato al momento dell’incasso.', defaultLanguage:'Lingua predefinita', timezone:'Fuso orario', venueGuestAccess:'Accesso ospiti del locale', roomQrCodes:'Codici QR delle camere', roomPreselected:'Camera preselezionata', signInDescription:'Accedi in modo sicuro per gestire il locale.', email:'E-mail', password:'Password', signIn:'Accedi', hostLogin:'Accesso host', requestDenied:'L’host non ha approvato questa richiesta.', requestWaiting:'L’host è stato avvisato. La pagina si aggiornerà automaticamente.', itemAdded:'Articolo aggiunto', poweredBy:'Fornito da Sky Bar',
  },
  en: {
    dashboard:'Dashboard', takeOrders:'Take orders', orders:'Open orders', bills:'Bills', guests:'Guests', rooms:'Rooms', products:'Products', requests:'Requests', account:'Account', settings:'Venue', logout:'Log out', total:'Total', items:'Items', add:'Add', save:'Save', cancel:'Cancel', confirm:'Confirm', close:'Close', edit:'Edit', remove:'Remove', print:'Print', settle:'Settle', cash:'Cash', card:'Card', other:'Other', pending:'Pending', language:'Language', offline:'Offline', synced:'Synced', selectRoom:'Select room', selectGuest:'Select guest', submitOrder:'Submit order', empty:'Nothing here yet', venueName:'Venue name', welcome:'Welcome', guestAccess:'Guest access', requestAccess:'Request access', selfService:'Self-service', undo:'Undo', approve:'Approve', deny:'Deny',
    today:'Today', viewAll:'View all', searchGuests:'Search guests…', selected:'selected', selectProducts:'Select products to build an order.', orderQueued:'Order saved offline and queued for sync.', orderAdded:'Order added.', note:'Note', live:'Live', archive:'Archive', searchBills:'Search by guest, room, or number…', loading:'Loading…', voidBill:'Void bill', voided:'Voided', bill:'Bill', guest:'Guest', date:'Date', host:'Host', reason:'Reason', reversalReason:'Reason for reversal', directory:'Directory', guestArchiveWarning:'This archives the guest and revokes their device access. Open orders must be resolved first.', configuration:'Configuration', roomName:'Room name', displayOrder:'Display order', catalog:'Catalog', categories:'Categories', germanName:'German name', description:'Description', price:'Price', category:'Category', enabledForOrders:'Enabled for new orders', enabled:'Enabled', disabled:'Disabled', liveQueue:'Live queue', linkGuest:'Link guest', createGuest:'Create new guest', linkTo:'Link to', accessExpires:'Access expires', profileCredentials:'Profile & credentials', currentPassword:'Current password', newPassword:'New password', passwordHint:'At least 12 characters', loggedInDevices:'Logged-in devices', thisDevice:'This device', lastActive:'Last active', revoke:'Revoke', hostAccounts:'Host accounts', active:'Active', inactive:'Disabled', enable:'Enable', disable:'Disable', addHost:'Add host', temporaryPassword:'Temporary password', role:'Role', staff:'Staff', admin:'Admin', createAccount:'Create account', accountUpdated:'Account updated.', permissionRequired:'Administrator permission required.', venueSaved:'Venue settings saved. New bills use the current name; historical bills remain unchanged.', venueIdentity:'Venue identity', venueIdentityHelp:'Sky Bar is the software name. The venue name is shown in billing and snapshotted onto each bill.', defaultLanguage:'Default language', timezone:'Timezone', venueGuestAccess:'Venue guest access', roomQrCodes:'Room QR codes', roomPreselected:'Room preselected', signInDescription:'Sign in securely to manage your venue.', email:'Email', password:'Password', signIn:'Sign in', hostLogin:'Host login', requestDenied:'The host did not approve this request.', requestWaiting:'The host has been notified. This page will update automatically.', itemAdded:'Item added', poweredBy:'Powered by Sky Bar',
  },
} as const;

type MessageKey = keyof typeof messages.de;
const I18nContext = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: MessageKey) => string } | null>(null);

function detectedLanguage(): Language {
  const saved = localStorage.getItem('skybar-language');
  if (saved === 'de' || saved === 'it' || saved === 'en') return saved;
  const device = navigator.language.slice(0, 2);
  return device === 'it' || device === 'en' ? device : 'de';
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, update] = useState<Language>(detectedLanguage);
  const value = useMemo(() => ({
    language,
    setLanguage: (next: Language) => { localStorage.setItem('skybar-language', next); document.documentElement.lang = next; update(next); },
    t: (key: MessageKey) => messages[language][key] ?? messages.de[key],
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error('I18nProvider is missing');
  return value;
}
